[package]
name = "abusedetector"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
trust-dns-resolver = "0.23"
regex = "1"
once_cell = "1"
