name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build release for"
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  # Validate the release before proceeding
  validate:
    name: Validate Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Validate version consistency
        run: |
          # Extract version from git tag
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG_VERSION="${{ github.event.inputs.tag }}"
            TAG_VERSION=${TAG_VERSION#v}
          else
            TAG_VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo "Tag version: $TAG_VERSION"

          # Extract version from Cargo.toml
          CARGO_VERSION=$(grep '^version = ' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
          echo "Cargo.toml version: $CARGO_VERSION"

          # Compare versions
          if [ "$TAG_VERSION" != "$CARGO_VERSION" ]; then
            echo "ERROR: Version mismatch!"
            echo "Git tag: v$TAG_VERSION"
            echo "Cargo.toml: $CARGO_VERSION"
            echo ""
            echo "Please ensure the version in Cargo.toml matches the git tag."
            echo "Expected: version = \"$TAG_VERSION\""
            exit 1
          fi

          echo "✓ Version consistency validated: $TAG_VERSION"

      - name: Validate build
        run: |
          cargo check --release --locked
          cargo test --all --all-features

  # Create the GitHub release
  create-release:
    name: Create GitHub Release
    needs: validate
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      tag_name: ${{ steps.get_tag.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get tag name
        id: get_tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag_name=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag_name }}
          release_name: Release ${{ steps.get_tag.outputs.tag_name }}
          draft: false
          prerelease: ${{ contains(steps.get_tag.outputs.tag_name, '-') }}
          body: |
            ## Changes

            See the [CHANGELOG](https://github.com/${{ github.repository }}/blob/${{ steps.get_tag.outputs.tag_name }}/CHANGELOG.md) for details.

            ## Installation

            Download the appropriate binary for your platform from the assets below.

            ### Linux/macOS
            ```bash
            # Make executable and move to PATH
            chmod +x abusedetector-*
            sudo mv abusedetector-* /usr/local/bin/abusedetector
            ```

            ### Windows
            ```powershell
            # Add to PATH or run directly
            .\abusedetector-windows-x86_64.exe --help
            ```

  # Build binaries for multiple platforms
  build-release:
    name: Build Release Binary
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: abusedetector
            asset_name: abusedetector-linux-x86_64
            cross: false
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: abusedetector
            asset_name: abusedetector-linux-x86_64-musl
            cross: true
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: abusedetector
            asset_name: abusedetector-linux-aarch64
            cross: true

          # macOS builds
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: abusedetector
            asset_name: abusedetector-macos-x86_64
            cross: false
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: abusedetector
            asset_name: abusedetector-macos-aarch64
            cross: false

          # Windows builds
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: abusedetector.exe
            asset_name: abusedetector-windows-x86_64.exe
            cross: false

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Cache cargo registry + build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-cargo-release-
            ${{ runner.os }}-${{ matrix.target }}-cargo-

      # Install cross for cross-compilation
      - name: Install cross
        if: matrix.cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      # Linux musl specific setup
      - name: Install musl tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      # Platform-specific setup for native compilation
      - name: Setup platform dependencies
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          echo "Windows setup - using vendored OpenSSL"

      - name: Build binary
        run: |
          if [ "${{ matrix.cross }}" = "true" ]; then
            cross build --release --target ${{ matrix.target }} --locked
          else
            cargo build --release --target ${{ matrix.target }} --locked
          fi
        shell: bash

      - name: Strip binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          if command -v strip >/dev/null 2>&1; then
            strip target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          fi

      - name: Prepare binary
        id: prepare_binary
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}
          else
            cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}
          fi

          # Get file size for upload
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            echo "binary_size=$(wc -c < '${{ matrix.asset_name }}' | tr -d ' ')" >> $GITHUB_OUTPUT
          else
            echo "binary_size=$(stat -f%z '${{ matrix.asset_name }}' 2>/dev/null || stat -c%s '${{ matrix.asset_name }}')" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: application/octet-stream

      # Create checksums for security
      - name: Generate checksums
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            certutil -hashfile ${{ matrix.asset_name }} SHA256 > ${{ matrix.asset_name }}.sha256
          else
            shasum -a 256 ${{ matrix.asset_name }} > ${{ matrix.asset_name }}.sha256
          fi
        shell: bash

      - name: Upload checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./${{ matrix.asset_name }}.sha256
          asset_name: ${{ matrix.asset_name }}.sha256
          asset_content_type: text/plain

  # Update release with checksums summary
  update-release:
    name: Update Release Description
    needs: [create-release, build-release]
    runs-on: ubuntu-latest
    if: always() && needs.create-release.result == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Update release description
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = '${{ needs.create-release.outputs.tag_name }}';

            // Get the release
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const release = releases.data.find(r => r.tag_name === tag);
            if (!release) {
              core.setFailed('Release not found');
              return;
            }

            // Get the assets
            const assets = await github.rest.repos.listReleaseAssets({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id,
            });

            // Build checksums section
            const checksumAssets = assets.data.filter(asset => asset.name.endsWith('.sha256'));
            let checksumSection = '';

            if (checksumAssets.length > 0) {
              checksumSection = '\n\n## Checksums (SHA256)\n\n';
              checksumSection += '```\n';

              for (const asset of checksumAssets) {
                const response = await github.rest.repos.getReleaseAsset({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  asset_id: asset.id,
                  headers: {
                    Accept: 'application/octet-stream'
                  }
                });

                // The response.data contains the checksum file content
                const checksum = Buffer.from(response.data).toString('utf8').trim();
                checksumSection += checksum + '\n';
              }

              checksumSection += '```\n';
            }

            // Update the release body
            const currentBody = release.body || '';
            const newBody = currentBody + checksumSection;

            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id,
              body: newBody
            });
